include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    # Allow logging/printing in a controlled fashion or suppress for debug calls
    public_member_api_docs: ignore
